language: haskell
ghc: 7.8.3

install:
 - sudo apt-cache policy happy
 - sudo apt-cache policy alex
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - export PATH=$PATH:/home/travis/build/NCrashed/hjass/.cabal-sandbox/bin
 - cabal install ./hashtables-1.0.1.8 --verbose
 - cabal install ./peggy-0.3.2 --verbose

script:
 - cabal build
 - cabal test
