language: haskell
ghc: 7.8.3

install:
 - sudo apt-cache policy happy
 - sudo apt-cache policy alex
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - export PATH=$PATH:/home/travis/build/NCrashed/hjass/.cabal-sandbox/bin
 - if !cabal install ./hashtables-1.0.1.8; then cat /home/travis/build/NCrashed/hjass/.cabal-sandbox/logs/hashtables-1.0.1.8.log; exit 1;fi
 - if !cabal install ./peggy-0.3.2; then cat cat /home/travis/build/NCrashed/hjass/.cabal-sandbox/logs/haskell-src-exts-1.16.0.1.log; cat /home/travis/build/NCrashed/hjass/.cabal-sandbox/logs/peggy-0.3.2.log; exit 1;fi
 
script:
 - cabal install --dependencies-only
 - cabal build
 - cabal test
