language: haskell
ghc: 7.8.3

install:
 - travis_retry sudo apt-get install --force-yes happy-1.19.0 alex-3.1.0
 - export PATH=/opt/alex/3.1.0/bin:/opt/happy/1.19.0/bin:$PATH
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal sandbox init
 - export PATH=$PATH:/home/travis/build/NCrashed/hjass/.cabal-sandbox/bin
 - cabal install ./hashtables-1.0.1.8 --verbose
 - cabal install ./peggy-0.3.2 --verbose

script:
 - cabal build
 - cabal test
