before_install:
 - travis_retry sudo apt-get install llvm-3.4 llvm-3.4-dev clang-3.4
 - travis_retry sudo apt-get update
 - wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
 - echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main'|sudo tee /etc/apt/sources.list.d/fpco.list
 - sudo apt-get update && sudo apt-get install stack -y

install:
 - stack setup
 - stack install --only-snapshot

script:
 - stack build 
 - stack test